# Generated by Django 4.1.2 on 2022-10-30 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shapefile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=1000)),
                ("file", models.FileField(upload_to="%Y/%M/%D")),
                ("uploaded_data", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
